name: Selenium Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'


      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Run Tests
        env:
          DISPLAY: :99
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 & pytest tests/
